name: Rust Multi-Arch Build

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            rustup_target: x86_64-unknown-linux-gnu
          - os: ubuntu-24.04-arm64
            target: aarch64-unknown-linux-gnu
            rustup_target: aarch64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            rustup_target: x86_64-pc-windows-msvc
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            rustup_target: aarch64-pc-windows-msvc
          - os: macos-13
            target: x86_64-apple-darwin
            rustup_target: x86_64-apple-darwin
          - os: macos-14
            target: aarch64-apple-darwin
            rustup_target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.rustup_target }}

    - name: Install Linux dependencies for Tao and Wry
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-24.04-arm64'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwebkit2gtk-4.1-dev \
          libappindicator3-dev \
          libgtk-3-dev

    - name: Build
      run: cargo build --release --target ${{ matrix.target }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ai-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/ai

    - name: Attach to GitHub Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: target/${{ matrix.target }}/release/ai
        name: ai-${{ matrix.target }}${{ matrix.target == 'x86_64-pc-windows-msvc' || matrix.target == 'aarch64-pc-windows-msvc' && '.exe' || '' }}
